FROM ubuntu:bionic@sha256:fd25e706f3dea2a5ff705dbc3353cf37f08307798f3e360a13e9385840f73fb3
RUN apt-get update && apt-get install -y curl
RUN curl --location https://gist.githubusercontent.com/deekayen/4148741/raw/98d35708fa344717d8eee15d11987de6c8e26d7d/1-1000.txt | while read -r line; do echo "$line"; sleep 0.1; done
RUN curl --location https://gist.githubusercontent.com/deekayen/4148741/raw/98d35708fa344717d8eee15d11987de6c8e26d7d/1-1000.txt | while read -r line; do echo "$line"; sleep 0.1; done
RUN curl --location https://gist.githubusercontent.com/deekayen/4148741/raw/98d35708fa344717d8eee15d11987de6c8e26d7d/1-1000.txt | while read -r line; do echo "$line"; sleep 0.1; done
